kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "172.31.1.166" # Replace with your private IP address
  apiServerPort: 33893
nodes:
- role: control-plane
  image: kindest/node:v1.34.3
- role: worker
  image: kindest/node:v1.34.3
- role: worker
  image: kindest/node:v1.34.3

  # commands
  # kind create cluster --name=iamsnyg-cluster --config=kind-cluster-config.yml
  # After creating the kind cluster
  # kubectl cluster-info --context kind-iamsnyg-cluster