apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-of-apps
  namespace: argocd
spec:
  sourceRepos:
  - 'https://github.com/iamsnyg/argocd-demos.git'
  destinations:
  - server: https://172.31.1.175:33893
    namespace: appsofapps
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: appsofapps-admin
    description: Admin role for apps-of-apps
    policies:
    - p, role:appsofapps-admin, applications, *, appsofapps/*, allow
